aliases: []
creation_timestamp: 1739515437368
current_stage: None
description: ''
last_updated_timestamp: 1739515437368
name: KNNclassifier
run_id: 14c5aa9caacd406ab4fa736bfbacd982
run_link: ''
source: file:///c:/Users/LENOVO/Desktop/Guvi_project/mlruns/403841464342790035/14c5aa9caacd406ab4fa736bfbacd982/artifacts/KNeighbors_model
status: READY
status_message: null
storage_location: file:///c:/Users/LENOVO/Desktop/Guvi_project/mlruns/403841464342790035/14c5aa9caacd406ab4fa736bfbacd982/artifacts/KNeighbors_model
user_id: null
version: 1
