aliases: []
creation_timestamp: 1736496046978
current_stage: None
description: ''
last_updated_timestamp: 1736496046978
name: AdaboostingRegressor
run_id: e9265aa52f574f8fb86c2a984f439a5a
run_link: ''
source: file:///c:/Users/LENOVO/Desktop/Guvi_project/mlruns/391970237538713523/e9265aa52f574f8fb86c2a984f439a5a/artifacts/AdaBoost_model
status: READY
status_message: null
storage_location: file:///c:/Users/LENOVO/Desktop/Guvi_project/mlruns/391970237538713523/e9265aa52f574f8fb86c2a984f439a5a/artifacts/AdaBoost_model
user_id: null
version: 2
