aliases: []
creation_timestamp: 1736496011634
current_stage: None
description: ''
last_updated_timestamp: 1736496011634
name: DecisionTree
run_id: a137b4068d33448fbea2616e200b8a13
run_link: ''
source: file:///c:/Users/LENOVO/Desktop/Guvi_project/mlruns/391970237538713523/a137b4068d33448fbea2616e200b8a13/artifacts/DecisionTree_model
status: READY
status_message: null
storage_location: file:///c:/Users/LENOVO/Desktop/Guvi_project/mlruns/391970237538713523/a137b4068d33448fbea2616e200b8a13/artifacts/DecisionTree_model
user_id: null
version: 3
